print ("JIMENEZ, Fayelynn S.")
print ("April 23, 1999")
print ("================================================")
print ("Marinduque State College")
print ("Bachelor of Science in Information Technology")
print ("2nd year")
print ("Section E")